(defun c:a2 (/ a i s apt thetext mspace) 
  (if 
    (setq s (ssget 
              '((0 . "CIRCLE,ELLIPSE,*POLYLINE,SPLINE")
                (-4 . "<NOT")
                (-4 . "<AND")
                (0 . "POLYLINE")
                (-4 . "&")
                (70 . 80)
                (-4 . "AND>")
                (-4 . "NOT>")
               )
            )
    )
    (progn 
      (setq mspace (vla-get-modelspace (vla-get-activedocument (vlax-get-acad-object ) ) ))
      (setq a 0.0)
      (repeat (setq i (sslength s)) 
        (setq a (+ a (vlax-curve-getarea (ssname s (setq i (1- i))))))
      )
      (princ "\nTotal Area: ")
      (princ (rtos a 2))
      (setq apt (getpoint "\nInsertion Point: "))
      (setq thetext (vla-AddText mspace (rtos a 2) (vlax-3d-point apt) 0.25))
    )
  )
  (princ)
)
(vl-load-com)
(princ)
